version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            make -C 0.X image
workflows:
  ci:
    jobs:
      - build
